# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfbcf45a9b94c157ad2026aed3702ec73e3f9f11c89fc9e288a29a6fa7bac6640e12fcaa2ae6dfd9d6578ddc12286033f48bc8887216cd0c3d30eb7d063104a3

test:
  secret_key_base: 18fddd41157da8e588e4d4555fc2bece2bb4fff50fbe9ff452aece306033e753c39e0680de7fa2fc9870d6866a06291657cd89b6270fdaa83c0ca4469ace5091

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
